# auth API

###
# baseURL
@baseURL = http://localhost:8000

###
# signup
POST {{baseURL}}/auth/signup
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234",
    "displayName": "test"
}

###
# signin
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
	"password": "test"
}

###
# create trip
POST {{baseURL}}/trip/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYjUzZjVlZGUyOTVkMTE2YWVkMDM4NyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2MDYxNDc4NDUsImV4cCI6MTYwNjE4Mzg0NX0.FmyVIPJzoNMSDmhnn33NMaOqD7n_WYHLfwGsm5Qcfkk

{
    "tripName": "Weekend in NYC",
	"data": []
}

###
# get all trips for given user
GET {{baseURL}}/trip/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYjUzZjVlZGUyOTVkMTE2YWVkMDM4NyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2MDYyNjkwMTQsImV4cCI6MTYwNjMwNTAxNH0.4ApNEM3Rz61sjKvGyTGGuYaaYYkyibvAfF6GxnNKnqQ

{
    "userId": "5fb53f5ede295d116aed0387"
}
